name: EventTools
version: '${project.version}'
main: me.commandrod.eventtools.Main
api-version: 1.17
authors: [ commandROD ]
description: Recreation of Skeppy's EventTools plugin.
website: https://github.com/commandrod/EventTools
